// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RecollectionModeMZ","status":true,"description":"回想モード機能を追加します。","parameters":{"recModeBgm":"","recModeBgmName":"blank_memories","recModeBgmPan":"0","recModeBgmPitch":"100","recModeBgmVolume":"90","recModeSelectWindow":"","recModeSelectWindowX":"260","recModeSelectWindowY":"180","recModeSelectWindowRecoTitle":"回想モード","recModeSelectWindowSelectReco":"回想を見る","recModeSelectWindowSelectCg":"CGを見る","recModeSelectWindowBackTitle":"タイトルに戻る","recModeList":"","recModeListItemColumn":"2","recModeListItemRow":"2","recModeListIsDisplayText":"true","recModeListDisplayPosition":"center","recModeListNeverWatchPictureName":"never_watch_picture","recModeListNeverWatchTextName":"？？？","sandboxMapId":"1","recoCgSettingList":"RecollectionModeMZData.json","devParameter":"","devParameterDevTools":"false"}}
];
